/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#584000",
        "surface-tint": "#8f4e00",
        "on-surface": "#211b10",
        "surface-container-high": "#f3e6d4",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#eee1cf",
        "on-surface-variant": "#554336",
        "inverse-primary": "#ffb77a",
        "error": "#ba1a1a",
        "background": "#fff8f3",
        "on-error-container": "#93000a",
        "outline": "#887364",
        "on-background": "#211b10",
        "surface-bright": "#fff8f3",
        "secondary-fixed-dim": "#ffb3ac",
        "surface-dim": "#e5d8c7",
        "surface-container-lowest": "#ffffff",
        "secondary": "#b6171e",
        "outline-variant": "#dbc2b0",
        "tertiary-fixed-dim": "#fabd00",
        "tertiary": "#785900",
        "on-primary-fixed-variant": "#6d3a00",
        "tertiary-container": "#e0a900",
        "on-tertiary-fixed-variant": "#5b4300",
        "on-primary-container": "#693800",
        "on-secondary-container": "#fffbff",
        "surface-container": "#f9ecda",
        "surface": "#fff8f3",
        "surface-container-low": "#fff2e0",
        "on-secondary-fixed-variant": "#930010",
        "on-secondary-fixed": "#410003",
        "tertiary-fixed": "#ffdf9e",
        "surface-variant": "#eee1cf",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#2e1500",
        "error-container": "#ffdad6",
        "primary": "#8f4e00",
        "secondary-container": "#da3433",
        "primary-fixed-dim": "#ffb77a",
        "on-error": "#ffffff",
        "primary-container": "#ff9933",
        "on-tertiary-fixed": "#261a00",
        "secondary-fixed": "#ffdad6",
        "primary-fixed": "#ffdcc2",
        "on-primary": "#ffffff",
        "inverse-surface": "#362f23",
        "inverse-on-surface": "#fcefdd"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
